[package]
name = "mio-tls-http"
version = "0.1.0"
edition = "2021"

[dependencies]
async-lock = "3.4.0"
mio = { version = "1.0.3", features = ["os-poll", "net"]}
rustls = "0.23.20"
rustls-pki-types = "1.10.1"
webpki-roots = "0.26.7"
